apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: mlops-api
type: Opaque
stringData:
  MLFLOW_TRACKING_URI: "http://mlflow-service.mlops-mlflow.svc.cluster.local:5000"
  MLFLOW_MODEL_NAME: "real_estate_champion"
  MLFLOW_CHAMPION_ALIAS: "champion"
  POSTGRES_RAW_CONN: "postgresql://mlops_user:mlops1234@postgres-service.mlops-data.svc.cluster.local:5432/raw_db"
  API_ADMIN_TOKEN: "changeme-admin-token"
  RELOAD_INTERVAL_SECONDS: "60"
  AWS_ACCESS_KEY_ID: "minioadmin"
  AWS_SECRET_ACCESS_KEY: "minioadmin123"
  MLFLOW_S3_ENDPOINT_URL: "http://minio-service.mlops-storage.svc.cluster.local:9000"
