apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: mlops-monitoring
  labels:
    app: grafana
data:
  datasource.yml: |
    apiVersion: 1

    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        access: proxy
        url: http://prometheus-service.mlops-monitoring.svc.cluster.local:9090
        isDefault: true
        editable: false
        jsonData:
          timeInterval: "15s"
