apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs
  namespace: mlops-data
  labels:
    app.kubernetes.io/part-of: mlops-platform
    app.kubernetes.io/component: airflow-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
