apiVersion: v1
kind: Secret
metadata:
  name: mlflow-secret
  namespace: mlops
type: Opaque
stringData:
  BACKEND_URI: postgresql://mlops_user:mlops1234@postgres-service:5432/mlflow_db
  ARTIFACT_URI: s3://mlflow
  AWS_ACCESS_KEY_ID: minioadmin
  AWS_SECRET_ACCESS_KEY: minioadmin123
  MLFLOW_S3_ENDPOINT_URL: http://minio-service:9000
