apiVersion: v1
kind: Secret
metadata:
  name: streamlit-secret
  namespace: mlops-ui
type: Opaque
stringData:
  API_URL: "http://inference-api-service.mlops-api.svc.cluster.local:8000"
  POSTGRES_CLEAN_CONN: "postgresql://mlops_user:mlops1234@postgres-service.mlops-data.svc.cluster.local:5432/mlops_db"
